### ISSUE TITLE
Error: Object: is not a legal argument to this wrapper, cause it doesn't respond to "read"

### ISSUE THREAD

**Issue by webmstr** [logstash-plugins/logstash-codec-gzip_lines#3]
There don't seem to be a lot of people talking about this codec in the wild, so maybe I'm suffering from a lack of examples.

I have this input:

```
file {
    type => "foo"
    path => "/path1/path2/*"
    codec => "gzip_lines"
}
```

I have installed the plugin, and logstash starts.

I've tested it with a single (valid, text) file in the directory, but I get messages like this:

```
{:timestamp=>"2016-01-06T09:30:16.917000-0800", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::File type=>\"foo\", path=>[\"/path1/path2/*\"], codec=><LogStash::Codecs::GzipLines charset=>\"UTF-8\">, debug=>false, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, start_position=>\"end\", delimiter=>\"\\n\">\n  Error: Object: \u001F\u008B\b\u0000ÑA\u008CV\u0000\u0003-Ê1\u000E\u00021\fDÑ\u009ESX¢vAË\u0001¸\u0006 is not a legal argument to this wrapper, cause it doesn't respond to \"read\".", :level=>:error}
```

Googling that error finds me some kindred spirits, but no clear answers.

**Comment by lukas1** [comment]
I have something very similar. My input for logstash is a tcp socket that accepts gzipped data. This is my input:
````
input {
	tcp {
		port => 4789
		codec => "gzip_lines"
	}
}
````
Instead of seeing uncompressed data in the output, I see this:
`a legal argument to this wrapper, cause it doesn't respond to "read"., :backtrace=>["org.jruby.util.IOInputStream.<init>(IOInputStream.java:64)", "org.jruby.ext.zlib.JZlibRubyGzipReader.initialize(JZlibRubyGzipReader.java:122)", "org.jruby.ext.zlib.JZlibRubyGzipReader.initialize19(JZlibRubyGzipReader.java:156)", "org.jruby.ext.zlib.JZlibRubyGzipReader$INVOKER$i$0$1$initialize19.call(JZlibRubyGzipReader$INVOKER$i$0$1$initialize19.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:679)", "org.jruby.RubyClass.finvoke(RubyClass.java:549)", "org.jruby.runtime.Helpers.invoke(Helpers.java:498)", "org.jruby.RubyObject.callInit(RubyObject.java:339)", "org.jruby.ext.zlib.JZlibRubyGzipReader.newInstance(JZlibRubyGzipReader.java:85)", "org.jruby.ext.zlib.JZlibRubyGzipReader$INVOKER$s$0$0$newInstance.call(JZlibRubyGzipReader$INVOKER$s$0$0$newInstance.gen)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)", "org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)", "org.jruby.ast.InstAsgnNode.interpret(InstAsgnNode.java:95)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:204)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:211)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)", "org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)", "org.jruby.ast.CallOneArgBlockNode.interpret(CallOneArgBlockNode.java:60)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.WhileNode.interpret(WhileNode.java:131)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)", "org.jruby.ast.RescueNode.interpret(RescueNode.java:116)", "org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)", "org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:126)", "org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:178)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:296)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:72)", "org.jruby.ast.FCallManyArgsNode.interpret(FCallManyArgsNode.java:60)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.ast.BlockNode.interpret(BlockNode.java:71)", "org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)", "org.jruby.ast.BeginNode.interpret(BeginNode.java:83)", "org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)", "org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)", "org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)", "org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)", "org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)", "org.jruby.runtime.Block.call(Block.java:101)", "org.jruby.RubyProc.call(RubyProc.java:300)", "org.jruby.RubyProc.call(RubyProc.java:230)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)", "java.lang.Thread.run(Thread.java:745)"`

I don't know whether the data that I send is somehow corrupt/not in the format gzip_lines expects (how do I find that out???). Or is it because gzip_lines codec can't be used in TCP source? Can anybody help please? Thank you.

**Comment by thasler** [comment]
We have the same issue using the codec in a rabbitmq input:

```
input {
	rabbitmq {
		host => "rabbitmqhost"
		exchange => "exchange_name"
		exchange_type => "topic"
		queue => "queue_name"
		user => "user"
		password => "pw"
		codec => "gzip_lines"
	}
} 
```
We want to send gzip compressed messages via rabbitmq to logstash and get the same error:
```
... is not a legal argument to this wrapper, cause it doesn't respond to "read".
Exception: Java::JavaLang::IllegalArgumentException
Stack: org.jruby.util.IOInputStream.<init>(IOInputStream.java:64)
```
We use Logstash 6.1.1 and logstash-codec-gzip_lines-3.0.3.
Does anybody know how to fix this?
Thanks.

**Comment by Rastalamm** [comment]
Running into the same issue.. 
`[logstash.inputs.file     ] observe_read_file: general error reading /file.xml.gz - error: java.lang.IllegalArgumentException: Object: ë¢RØù)ólZÍP±nÌ×ÆÚAXÛrªD¬ÅfÓ8�÷¼<ñI­_·" is not a legal argument to this wrapper, cause it doesn't respond to "read".`
